export const STICKER_PACKS = {
  "Classic": [
    { id: "thumbs_up", emoji: "👍", label: "Thumbs Up" },
    { id: "thumbs_down", emoji: "👎", label: "Thumbs Down" },
    { id: "heart", emoji: "❤️", label: "Heart" },
    { id: "fire", emoji: "🔥", label: "Fire" },
    { id: "clap", emoji: "👏", label: "Clap" },
    { id: "wave", emoji: "👋", label: "Wave" },
    { id: "laugh", emoji: "😂", label: "Laugh" },
    { id: "cry", emoji: "😭", label: "Cry" },
    { id: "angry", emoji: "😡", label: "Angry" },
    { id: "love", emoji: "😍", label: "Love" },
    { id: "think", emoji: "🤔", label: "Think" },
    { id: "party", emoji: "🎉", label: "Party" },
    { id: "rocket", emoji: "🚀", label: "Rocket" },
    { id: "star", emoji: "⭐", label: "Star" },
    { id: "check", emoji: "✅", label: "Check" },
    { id: "eyes", emoji: "👀", label: "Eyes" },
  ],
  "Reactions": [
    { id: "haha", emoji: "🤣", label: "Haha" },
    { id: "wow", emoji: "😮", label: "Wow" },
    { id: "sad", emoji: "😢", label: "Sad" },
    { id: "cool", emoji: "😎", label: "Cool" },
    { id: "nerd", emoji: "🤓", label: "Nerd" },
    { id: "sleep", emoji: "😴", label: "Sleep" },
    { id: "sick", emoji: "🤒", label: "Sick" },
    { id: "ghost", emoji: "👻", label: "Ghost" },
    { id: "devil", emoji: "😈", label: "Devil" },
    { id: "angel", emoji: "😇", label: "Angel" },
    { id: "robot", emoji: "🤖", label: "Robot" },
    { id: "alien", emoji: "👽", label: "Alien" },
    { id: "poop", emoji: "💩", label: "Poop" },
    { id: "clown", emoji: "🤡", label: "Clown" },
    { id: "skull", emoji: "💀", label: "Skull" },
    { id: "hundred", emoji: "💯", label: "100" },
  ],
  "Gestures": [
    { id: "ok", emoji: "👌", label: "OK" },
    { id: "peace", emoji: "✌️", label: "Peace" },
    { id: "crossed", emoji: "🤞", label: "Crossed" },
    { id: "shaka", emoji: "🤙", label: "Shaka" },
    { id: "fist", emoji: "✊", label: "Fist" },
    { id: "punch", emoji: "👊", label: "Punch" },
    { id: "muscle", emoji: "💪", label: "Muscle" },
    { id: "pray", emoji: "🙏", label: "Pray" },
    { id: "point_up", emoji: "☝️", label: "Point Up" },
    { id: "point_down", emoji: "👇", label: "Point Down" },
    { id: "point_left", emoji: "👈", label: "Point Left" },
    { id: "point_right", emoji: "👉", label: "Point Right" },
    { id: "vulcan", emoji: "🖖", label: "Vulcan" },
    { id: "metal", emoji: "🤘", label: "Metal" },
    { id: "call_me", emoji: "📞", label: "Call Me" },
    { id: "raised_hand", emoji: "✋", label: "Raised Hand" },
  ],
  "Fun": [
    { id: "confetti", emoji: "🎊", label: "Confetti" },
    { id: "balloon", emoji: "🎈", label: "Balloon" },
    { id: "gift", emoji: "🎁", label: "Gift" },
    { id: "trophy", emoji: "🏆", label: "Trophy" },
    { id: "medal", emoji: "🥇", label: "Medal" },
    { id: "crown", emoji: "👑", label: "Crown" },
    { id: "diamond", emoji: "💎", label: "Diamond" },
    { id: "lightning", emoji: "⚡", label: "Lightning" },
    { id: "boom", emoji: "💥", label: "Boom" },
    { id: "sparkles", emoji: "✨", label: "Sparkles" },
    { id: "rainbow", emoji: "🌈", label: "Rainbow" },
    { id: "sun", emoji: "☀️", label: "Sun" },
    { id: "moon", emoji: "🌙", label: "Moon" },
    { id: "snowflake", emoji: "❄️", label: "Snowflake" },
    { id: "clover", emoji: "🍀", label: "Clover" },
    { id: "mushroom", emoji: "🍄", label: "Mushroom" },
  ],
};
